disabled_rules: # rule identifiers to exclude from running
- identifier_name
- cyclomatic_complexity
- function_body_length
- type_body_length
- file_length
- force_cast
- function_parameter_count
- implicit_getter
- nesting

opt_in_rules: # some rules are only opt-in
- closure_end_indentation
- implicit_return
- literal_expression_end_indentation
- modifier_order
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiple_closures_with_trailing_closure
- vertical_parameter_alignment_on_call

included: # paths to include during linting. `--path` is ignored if present.
- CoffeeChat

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- CoffeeChat/AppDelegate.swift

line_length:
- 130 # warning
- 200 # error

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
- 3
- 4
